[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.scripts]
redact_anon_file = "redact_client.__main__:anonymize_file_entry_point"
redact_anon_folder = "redact_client.__main__:anonymize_folder_entry_point"

[tool.flit.metadata]
module = "redact_client"
author = "brighter AI"
author-email = "dev@brighter.ai"
home-page = "https://github.com/brighter-ai"
requires-python = ">=3.6"
requires = [
    "pydantic~=1.6.1",
    "requests~=2.24.0",
    "tqdm~=4.52.0",
    "typer~=0.3.2"
]
